### ISSUE TITLE
Uninstallable...

### ISSUE THREAD

**Issue by YoshiBoiAdvance** [FailedShack/USBHelperInstaller#1] opened 2019-06-08 08:14 UTC
So, WHY THE HELL THE SETUP DOES NOT INSTALL ANYTHING?!

**Comment by FailedShack** [comment] 2019-06-08 20:54
First of all, you should know that this project is open-source, so if you're feeling that strongly about it, feel free to contribute to it yourself.

Secondly, do you mean it doesn't install anything as in an error appears or in the install process completes successfully but nothing appears to be installed?

If it's the former, unfortunately, seems to be somewhat of a common occurrence. I believe it could be due to archive.org often being overloaded. It could also be due to the ISP blocking access to either it or GitHub, which wouldn't appear to be your case.

That said, using the installer is not a requirement to use USBHelperLauncher, it's there mostly for convenience. You can set-up USBHelperLauncher manually:

Step 1. Download the [launcher](https://github.com/FailedShack/USBHelperLauncher/releases/latest).
Step 2. Download [Wii U USB Helper](https://archive.org/download/WiiUUSBHelper/Wii%20U%20USB%20Helper%200.6.1.653.zip).
Step 3. Extract the helper, then the launcher in the same folder.
Step 4. Run USBHelperLauncher.exe and follow the on-screen instructions. Make a shortcut of it on the desktop.

**Comment by FailedShack** [comment] 2019-06-20 17:47
Request for additional information unanswered, closing as unable to reproduce.

**Comment by FailedShack** [comment] 2019-06-20 17:47
Request for additional information unanswered, closing as unable to reproduce.

**Closed by FailedShack** 2019-06-20 17:47 UTC
Labels: question

**Comment by labaland** [comment] 2021-02-08 15:50
My program is instant crashing/freezes when i try to press "add" game, or when closing the program. Any idea why? :)

**Comment by labaland** [comment] 2021-02-08 15:50
My program is instant crashing/freezes when i try to press "add" game, or when closing the program. Any idea why? :)
